[package]
name = "scorton-compliance"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
